### ISSUE TITLE
LICENSE doesn't contain a date or copyright holder

### ISSUE THREAD

**Issue by ghalfacree** [CSAIL-Arch-Sec/DAGguise#1]
The LICENSE file included in this repository reads, in its top line:

```
Copyright (c) <date> <copyright holder>
```

This should be edited with the year(s) of development and the name of the copyright holder.

**Comment by peterdeutsch** [comment]
We leave the license unmodified from the base implementation of gem5.

https://github.com/gem5/gem5/blob/stable/LICENSE
